#ifndef VIDEOCAPTURE_GLOBAL_H
#define VIDEOCAPTURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIDEOCAPTURE_LIBRARY)
#  define VIDEOCAPTURESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIDEOCAPTURESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIDEOCAPTURE_GLOBAL_H
